# Generated by Django 4.1.1 on 2022-09-29 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('cedula_aux', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_1', models.CharField(max_length=20)),
                ('apellido_2', models.CharField(max_length=20)),
                ('numtel_aux', models.CharField(max_length=10)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auxiliar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('cedula_enfe', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_1', models.CharField(max_length=20)),
                ('apellido_2', models.CharField(max_length=20)),
                ('numtel_enfe', models.CharField(max_length=10)),
                ('Auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enfermero', to='apphos.auxiliar')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enfermero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('cedula_fam', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_1', models.CharField(max_length=20)),
                ('apellido_2', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=30)),
                ('Auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Familiar', to='apphos.auxiliar')),
            ],
        ),
        migrations.CreateModel(
            name='Historia_clinica',
            fields=[
                ('id_historia', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=1000)),
                ('sugerencia', models.CharField(max_length=1000)),
                ('Familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Historia_clinica', to='apphos.familiar')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('cedula_med', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_1', models.CharField(max_length=20)),
                ('apellido_2', models.CharField(max_length=20)),
                ('numtel_med', models.CharField(max_length=10)),
                ('Auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medico', to='apphos.auxiliar')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula_pac', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_1', models.CharField(max_length=20)),
                ('apellido_2', models.CharField(max_length=20)),
                ('fecha_nto', models.CharField(max_length=20)),
                ('direccion_pac', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('numtel_pac', models.CharField(max_length=10)),
                ('Auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='apphos.auxiliar')),
                ('Enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='apphos.enfermero')),
                ('cedula_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='apphos.medico')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signos_vitales',
            fields=[
                ('Id_signos', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=25)),
                ('Hora', models.CharField(max_length=25)),
                ('Oximetria', models.CharField(max_length=25)),
                ('Frec_respirato', models.CharField(max_length=25)),
                ('Frec_cardiaca', models.CharField(max_length=25)),
                ('Temperatura', models.CharField(max_length=25)),
                ('presion_arterial', models.CharField(max_length=25)),
                ('Glisemia', models.CharField(max_length=25)),
                ('Familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Signos_vitales', to='apphos.familiar')),
                ('Historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Signos_vitales', to='apphos.historia_clinica')),
                ('cedula_pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Signos_vitales', to='apphos.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='Medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Historia_clinica', to='apphos.medico'),
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='cedula_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Historia_clinica', to='apphos.paciente'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='cedula_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Familiar', to='apphos.paciente'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Familiar', to=settings.AUTH_USER_MODEL),
        ),
    ]
